### ISSUE TITLE
Scraper or data entry for Dec. 11, 2007 U.S. House special general election

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-oh#1]
County-level data only, HTML table is [here](http://www.sos.state.oh.us/sos/elections/Research/electResultsMain/2007ElectionsResults/07-1211fifthCongressional.aspx). Things to know:

* Output file is named `20111207__oh__special__general__house__5.csv`
* Headers should be: county, candidate, party, office, district, votes, pct. Use `U.S. House` as office.
* Only include candidate totals, don't include county totals.

**Comment by bsweger** [comment]
I just wrote a scraper for this, but @dwillis beat me to it. I love that you've tagged issues good for new contributors and people who can't devote a lot of time. Would it possible to comment or label in-progress issues to prevent duplicate work? (Applies to me too, since I started this yesterday but didn't bother to say so).

**Comment by dwillis** [comment]
Oh, absolutely, and I'm sorry that I stepped your toes!

**Comment by bsweger** [comment]
No worries--the scraper worked on the Nov. special election results, so I just submitted those instead.
